apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
type: Opaque
stringData:
  # 👇 Adicionado o ".default.svc.cluster.local" após o nome do banco
  DATABASE_URL: "postgresql://postgres:postgres@oficina-db.default.svc.cluster.local:5432/oficina_db?schema=public"
  JWT_SECRET: "seu-segredo-super-seguro-aqui"